jobs:
  include:

  - os: linux
    dist: xenial
    compiler: gcc
    language: python
    python: "3.7"
    env:
    - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    addons:
      apt:
        sources:
        - sourceline: 'ppa:ubuntu-toolchain-r/test'
        - sourceline: 'ppa:beineri/opt-qt-5.12.3-xenial'
        packages:
        - g++-7
        - qt512-meta-full
        - mesa-common-dev
        - libglu1-mesa-dev
        - lcov
        update: true
    before_install:
    - export CC
    - export CXX
    - eval "${MATRIX_EVAL}"
    install:
    - source /opt/qt512/bin/qt512-env.sh
    - pip3 install conan
    - conan user
    - conan profile new default --detect --force
    - conan profile update settings.compiler.libcxx=libstdc++11 default
  
  - os: osx
    language: c++
    osx_image: xcode10.1
    addons:
      homebrew:
        packages:
        - lcov
        update: true
    install:
    - brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/65a45a9e/Formula/qt.rb
    - export QTDIR="/usr/local/opt/qt"
    - export PATH="$QTDIR/bin:$PATH"
    - pip3 install conan

script:
- cmake . -G "Unix Makefiles" -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release
- cmake --build .
- ctest .
- cmake --build . --target coverage
