language: python
python: "3.7"
dist: xenial
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: osx
      osx_image: xcode10.1
    
before_install:
  - export CC
  - export CXX
  - eval "${MATRIX_EVAL}"
install:
  - pip install conan
  - conan user
  - conan profile new default --detect --force
  - conan profile update settings.compiler.libcxx=libstdc++11 default
script:
  - cmake . -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
  - cmake --build .
  - ctest .