jobs:
  include:
    - os: linux
      language: python
      python: "3.7"
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      cache:
        directories:
          - /opt/qt512
      before_install:
        - export CC
        - export CXX
        - eval "${MATRIX_EVAL}"
      install:
        - |
          if [[ ! -f /opt/qt512/bin/qmake ]]; then
            sudo add-apt-repository -y ppa:beineri/opt-qt-5.12.3-xenial
            sudo apt-get update
            sudo apt-get -y install qt512-meta-full mesa-common-dev libglu1-mesa-dev
          fi
        - source /opt/qt512/bin/qt512-env.sh
        - pip install conan
        - conan user
        - conan profile new default --detect --force
        - conan profile update settings.compiler.libcxx=libstdc++11 default
    
    - os: osx
      language: c++
      osx_image: xcode10.1
      cache:
        directories:
          - /usr/local/opt/qt
      install:
        - |
          if [[ ! -f /usr/local/opt/qt/bin/qmake ]]; then
            brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/65a45a9e/Formula/qt.rb
          fi
        - export QTDIR="/usr/local/opt/qt"
        - export PATH="$QTDIR/bin:$PATH"
        - pip3 install conan

script:
  - cmake . -G "Unix Makefiles" -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release
  - cmake --build .
  - ctest .