language: c++

python: "3.7"

dist: bionic

compiler: gcc

install:
  - pip install conan
  - conan user
  - conan profile new default --detect --force
  - conan profile update settings.compiler.libcxx=libstdc++11 default

script:
  - mkdir /tmp/build
  - cd /tmp/build
  - cmake ${TRAVIS_BUILD_DIR}
  - cmake --build . || travis_terminate 1;  